### ISSUE TITLE
なぜGhostはグラムを㌘にしてしまうのか？

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#60]
エントリーのソースを見たら`プログラム`のままなんだけど、ブラウザで表示させると`プロ㌘`になってしまう。
これはCSSのせいだな。

```
<link rel="stylesheet" type="text/css" href="/assets/css/screen.css?v=e806c19af1" />
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Merriweather:300,700,700italic,300italic|Open+Sans:700,400" />
```
このどちらかを削除してみればわかると思うけど、どうするのが簡単だろう。

**Comment by 630E6617** [comment]
content/theme/casper/default.hbsを書き換えて`systemctl restart ghost`で結果を見ることができる。結果1行目の`assets/css/screen.css`が問題ということがわかった。この[screen.css](https://github.com/TryGhost/Casper/blob/master/assets/css/screen.css)は2000行ある。

**Comment by 630E6617** [comment]
```
    -webkit-font-feature-settings: 'dlig' 1, 'liga' 1, 'lnum' 1, 'kern' 1;                        
    -moz-font-feature-settings: 'dlig' 1, 'liga' 1, 'lnum' 1, 'kern' 1;                           
    -o-font-feature-settings: 'dlig' 1, 'liga' 1, 'lnum' 1, 'kern' 1;                             
```
この中の`liga`か？ リガチャーか？

**Comment by 630E6617** [comment]
### 解決
bug report/feature request出そうかと思ったけど、SETTING :arrow_right:  Code Injectionで
```CSS
<style type="text/css">
h1, h2, h3,                                                                                         
h4, h5, h6 {
    -webkit-font-feature-settings: 'dlig' 0, 'liga' 1, 'lnum' 1, 'kern' 1;
    -moz-font-feature-settings: 'dlig' 0, 'liga' 1, 'lnum' 1, 'kern' 1;
    -o-font-feature-settings: 'dlig' 0, 'liga' 1, 'lnum' 1, 'kern' 1;
    color: #2E2E2E;
    line-height: 1.15em;
    margin: 0 0 0.4em 0;
    font-family: "Open Sans", sans-serif;
    text-rendering: geometricPrecision;
}
</style>
```
とすれば対応できますな。これでいいか。
